print("Hello!")
print("This message is made by Pythascript.")
print("There are some things you cannot do with Pythascript, such as input(),")
print("but you can still do many things with Pythascript!")
print("Good luck on your first voyage!")
